/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuildsGuildIdRouteImport } from './routes/guilds/$guildId'
import { Route as GuildsGuildIdIndexRouteImport } from './routes/guilds/$guildId.index'
import { Route as GuildsGuildIdActionFailuresRouteImport } from './routes/guilds/$guildId.action-failures'
import { Route as GuildsGuildIdAppealsRouteImport } from './routes/guilds/$guildId.appeals'
import { Route as GuildsGuildIdAuditLogRouteImport } from './routes/guilds/$guildId.audit-log'
import { Route as GuildsGuildIdCasesRouteImport } from './routes/guilds/$guildId.cases'
import { Route as GuildsGuildIdSettingsRouteImport } from './routes/guilds/$guildId.settings'
import { Route as GuildsGuildIdTemplatesRouteImport } from './routes/guilds/$guildId.templates'
import { Route as GuildsGuildIdCasesCaseRefRouteImport } from './routes/guilds/$guildId.cases.$caseRef'
import { Route as GuildsGuildIdMembersMemberIdRouteImport } from './routes/guilds/$guildId.members.$memberId'
import { Route as MembersGuildsGuildIdCasesRouteImport } from './routes/members/guilds/$guildId.cases'
import { Route as GuildsGuildIdCasesCaseRefAppealRouteImport } from './routes/guilds/$guildId.cases.$caseRef.appeal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsGuildIdRoute = GuildsGuildIdRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsGuildIdIndexRoute = GuildsGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdActionFailuresRoute =
  GuildsGuildIdActionFailuresRouteImport.update({
    id: '/action-failures',
    path: '/action-failures',
    getParentRoute: () => GuildsGuildIdRoute,
  } as any)
const GuildsGuildIdAppealsRoute = GuildsGuildIdAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdAuditLogRoute = GuildsGuildIdAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdCasesRoute = GuildsGuildIdCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdSettingsRoute = GuildsGuildIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdTemplatesRoute = GuildsGuildIdTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdCasesCaseRefRoute =
  GuildsGuildIdCasesCaseRefRouteImport.update({
    id: '/$caseRef',
    path: '/$caseRef',
    getParentRoute: () => GuildsGuildIdCasesRoute,
  } as any)
const GuildsGuildIdMembersMemberIdRoute =
  GuildsGuildIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => GuildsGuildIdRoute,
  } as any)
const MembersGuildsGuildIdCasesRoute =
  MembersGuildsGuildIdCasesRouteImport.update({
    id: '/members/guilds/$guildId/cases',
    path: '/members/guilds/$guildId/cases',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuildsGuildIdCasesCaseRefAppealRoute =
  GuildsGuildIdCasesCaseRefAppealRouteImport.update({
    id: '/appeal',
    path: '/appeal',
    getParentRoute: () => GuildsGuildIdCasesCaseRefRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/guilds/$guildId/action-failures': typeof GuildsGuildIdActionFailuresRoute
  '/guilds/$guildId/appeals': typeof GuildsGuildIdAppealsRoute
  '/guilds/$guildId/audit-log': typeof GuildsGuildIdAuditLogRoute
  '/guilds/$guildId/cases': typeof GuildsGuildIdCasesRouteWithChildren
  '/guilds/$guildId/settings': typeof GuildsGuildIdSettingsRoute
  '/guilds/$guildId/templates': typeof GuildsGuildIdTemplatesRoute
  '/guilds/$guildId/': typeof GuildsGuildIdIndexRoute
  '/guilds/$guildId/cases/$caseRef': typeof GuildsGuildIdCasesCaseRefRouteWithChildren
  '/guilds/$guildId/members/$memberId': typeof GuildsGuildIdMembersMemberIdRoute
  '/members/guilds/$guildId/cases': typeof MembersGuildsGuildIdCasesRoute
  '/guilds/$guildId/cases/$caseRef/appeal': typeof GuildsGuildIdCasesCaseRefAppealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guilds/$guildId/action-failures': typeof GuildsGuildIdActionFailuresRoute
  '/guilds/$guildId/appeals': typeof GuildsGuildIdAppealsRoute
  '/guilds/$guildId/audit-log': typeof GuildsGuildIdAuditLogRoute
  '/guilds/$guildId/cases': typeof GuildsGuildIdCasesRouteWithChildren
  '/guilds/$guildId/settings': typeof GuildsGuildIdSettingsRoute
  '/guilds/$guildId/templates': typeof GuildsGuildIdTemplatesRoute
  '/guilds/$guildId': typeof GuildsGuildIdIndexRoute
  '/guilds/$guildId/cases/$caseRef': typeof GuildsGuildIdCasesCaseRefRouteWithChildren
  '/guilds/$guildId/members/$memberId': typeof GuildsGuildIdMembersMemberIdRoute
  '/members/guilds/$guildId/cases': typeof MembersGuildsGuildIdCasesRoute
  '/guilds/$guildId/cases/$caseRef/appeal': typeof GuildsGuildIdCasesCaseRefAppealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/guilds/$guildId/action-failures': typeof GuildsGuildIdActionFailuresRoute
  '/guilds/$guildId/appeals': typeof GuildsGuildIdAppealsRoute
  '/guilds/$guildId/audit-log': typeof GuildsGuildIdAuditLogRoute
  '/guilds/$guildId/cases': typeof GuildsGuildIdCasesRouteWithChildren
  '/guilds/$guildId/settings': typeof GuildsGuildIdSettingsRoute
  '/guilds/$guildId/templates': typeof GuildsGuildIdTemplatesRoute
  '/guilds/$guildId/': typeof GuildsGuildIdIndexRoute
  '/guilds/$guildId/cases/$caseRef': typeof GuildsGuildIdCasesCaseRefRouteWithChildren
  '/guilds/$guildId/members/$memberId': typeof GuildsGuildIdMembersMemberIdRoute
  '/members/guilds/$guildId/cases': typeof MembersGuildsGuildIdCasesRoute
  '/guilds/$guildId/cases/$caseRef/appeal': typeof GuildsGuildIdCasesCaseRefAppealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guilds/$guildId'
    | '/guilds/$guildId/action-failures'
    | '/guilds/$guildId/appeals'
    | '/guilds/$guildId/audit-log'
    | '/guilds/$guildId/cases'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/templates'
    | '/guilds/$guildId/'
    | '/guilds/$guildId/cases/$caseRef'
    | '/guilds/$guildId/members/$memberId'
    | '/members/guilds/$guildId/cases'
    | '/guilds/$guildId/cases/$caseRef/appeal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guilds/$guildId/action-failures'
    | '/guilds/$guildId/appeals'
    | '/guilds/$guildId/audit-log'
    | '/guilds/$guildId/cases'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/templates'
    | '/guilds/$guildId'
    | '/guilds/$guildId/cases/$caseRef'
    | '/guilds/$guildId/members/$memberId'
    | '/members/guilds/$guildId/cases'
    | '/guilds/$guildId/cases/$caseRef/appeal'
  id:
    | '__root__'
    | '/'
    | '/guilds/$guildId'
    | '/guilds/$guildId/action-failures'
    | '/guilds/$guildId/appeals'
    | '/guilds/$guildId/audit-log'
    | '/guilds/$guildId/cases'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/templates'
    | '/guilds/$guildId/'
    | '/guilds/$guildId/cases/$caseRef'
    | '/guilds/$guildId/members/$memberId'
    | '/members/guilds/$guildId/cases'
    | '/guilds/$guildId/cases/$caseRef/appeal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuildsGuildIdRoute: typeof GuildsGuildIdRouteWithChildren
  MembersGuildsGuildIdCasesRoute: typeof MembersGuildsGuildIdCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId': {
      id: '/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof GuildsGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId/': {
      id: '/guilds/$guildId/'
      path: '/'
      fullPath: '/guilds/$guildId/'
      preLoaderRoute: typeof GuildsGuildIdIndexRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/action-failures': {
      id: '/guilds/$guildId/action-failures'
      path: '/action-failures'
      fullPath: '/guilds/$guildId/action-failures'
      preLoaderRoute: typeof GuildsGuildIdActionFailuresRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/appeals': {
      id: '/guilds/$guildId/appeals'
      path: '/appeals'
      fullPath: '/guilds/$guildId/appeals'
      preLoaderRoute: typeof GuildsGuildIdAppealsRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/audit-log': {
      id: '/guilds/$guildId/audit-log'
      path: '/audit-log'
      fullPath: '/guilds/$guildId/audit-log'
      preLoaderRoute: typeof GuildsGuildIdAuditLogRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/cases': {
      id: '/guilds/$guildId/cases'
      path: '/cases'
      fullPath: '/guilds/$guildId/cases'
      preLoaderRoute: typeof GuildsGuildIdCasesRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/settings': {
      id: '/guilds/$guildId/settings'
      path: '/settings'
      fullPath: '/guilds/$guildId/settings'
      preLoaderRoute: typeof GuildsGuildIdSettingsRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/templates': {
      id: '/guilds/$guildId/templates'
      path: '/templates'
      fullPath: '/guilds/$guildId/templates'
      preLoaderRoute: typeof GuildsGuildIdTemplatesRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/cases/$caseRef': {
      id: '/guilds/$guildId/cases/$caseRef'
      path: '/$caseRef'
      fullPath: '/guilds/$guildId/cases/$caseRef'
      preLoaderRoute: typeof GuildsGuildIdCasesCaseRefRouteImport
      parentRoute: typeof GuildsGuildIdCasesRoute
    }
    '/guilds/$guildId/members/$memberId': {
      id: '/guilds/$guildId/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/guilds/$guildId/members/$memberId'
      preLoaderRoute: typeof GuildsGuildIdMembersMemberIdRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/members/guilds/$guildId/cases': {
      id: '/members/guilds/$guildId/cases'
      path: '/members/guilds/$guildId/cases'
      fullPath: '/members/guilds/$guildId/cases'
      preLoaderRoute: typeof MembersGuildsGuildIdCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId/cases/$caseRef/appeal': {
      id: '/guilds/$guildId/cases/$caseRef/appeal'
      path: '/appeal'
      fullPath: '/guilds/$guildId/cases/$caseRef/appeal'
      preLoaderRoute: typeof GuildsGuildIdCasesCaseRefAppealRouteImport
      parentRoute: typeof GuildsGuildIdCasesCaseRefRoute
    }
  }
}

interface GuildsGuildIdCasesCaseRefRouteChildren {
  GuildsGuildIdCasesCaseRefAppealRoute: typeof GuildsGuildIdCasesCaseRefAppealRoute
}

const GuildsGuildIdCasesCaseRefRouteChildren: GuildsGuildIdCasesCaseRefRouteChildren =
  {
    GuildsGuildIdCasesCaseRefAppealRoute: GuildsGuildIdCasesCaseRefAppealRoute,
  }

const GuildsGuildIdCasesCaseRefRouteWithChildren =
  GuildsGuildIdCasesCaseRefRoute._addFileChildren(
    GuildsGuildIdCasesCaseRefRouteChildren,
  )

interface GuildsGuildIdCasesRouteChildren {
  GuildsGuildIdCasesCaseRefRoute: typeof GuildsGuildIdCasesCaseRefRouteWithChildren
}

const GuildsGuildIdCasesRouteChildren: GuildsGuildIdCasesRouteChildren = {
  GuildsGuildIdCasesCaseRefRoute: GuildsGuildIdCasesCaseRefRouteWithChildren,
}

const GuildsGuildIdCasesRouteWithChildren =
  GuildsGuildIdCasesRoute._addFileChildren(GuildsGuildIdCasesRouteChildren)

interface GuildsGuildIdRouteChildren {
  GuildsGuildIdActionFailuresRoute: typeof GuildsGuildIdActionFailuresRoute
  GuildsGuildIdAppealsRoute: typeof GuildsGuildIdAppealsRoute
  GuildsGuildIdAuditLogRoute: typeof GuildsGuildIdAuditLogRoute
  GuildsGuildIdCasesRoute: typeof GuildsGuildIdCasesRouteWithChildren
  GuildsGuildIdSettingsRoute: typeof GuildsGuildIdSettingsRoute
  GuildsGuildIdTemplatesRoute: typeof GuildsGuildIdTemplatesRoute
  GuildsGuildIdIndexRoute: typeof GuildsGuildIdIndexRoute
  GuildsGuildIdMembersMemberIdRoute: typeof GuildsGuildIdMembersMemberIdRoute
}

const GuildsGuildIdRouteChildren: GuildsGuildIdRouteChildren = {
  GuildsGuildIdActionFailuresRoute: GuildsGuildIdActionFailuresRoute,
  GuildsGuildIdAppealsRoute: GuildsGuildIdAppealsRoute,
  GuildsGuildIdAuditLogRoute: GuildsGuildIdAuditLogRoute,
  GuildsGuildIdCasesRoute: GuildsGuildIdCasesRouteWithChildren,
  GuildsGuildIdSettingsRoute: GuildsGuildIdSettingsRoute,
  GuildsGuildIdTemplatesRoute: GuildsGuildIdTemplatesRoute,
  GuildsGuildIdIndexRoute: GuildsGuildIdIndexRoute,
  GuildsGuildIdMembersMemberIdRoute: GuildsGuildIdMembersMemberIdRoute,
}

const GuildsGuildIdRouteWithChildren = GuildsGuildIdRoute._addFileChildren(
  GuildsGuildIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuildsGuildIdRoute: GuildsGuildIdRouteWithChildren,
  MembersGuildsGuildIdCasesRoute: MembersGuildsGuildIdCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
